### ISSUE TITLE
Message Not Sending due to server error

### ISSUE THREAD

**Issue by kimvdm** [moozzyk/SignalRSwiftCourse#1]
When sending a message to the running server, I got the following error given the current code:

Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[22]
      Parameters to hub method 'Broadcast' are incorrect.
      System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
       ---> System.Text.Json.JsonException: The JSON value could not be converted to TestServer.Message. Path: $ | LineNumber: 0 | BytePositionInLine: 5.
         at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
         at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)

fixed this error by implementing the following changes to index.html:

` hubConnection.on('NewMessage', (message) => {
        var child = document.createElement('li');
        child.innerHTML = `<strong>${message.name}</strong>:&nbsp;&nbsp;${message.text}</li>`;
        document.getElementById('discussion').appendChild(child);
    });

    hubConnection.start().then(() => {
        document.getElementById('sendmessage').addEventListener('click', event => {
            let messageTextBox = document.getElementById('message');
            let message = {
                Name: name,
                Text: messageTextBox.value
            };
            hubConnection.invoke('Broadcast', message);
            messageTextBox.value = "";
            event.preventDefault();
        });
    })`

**Comment by moozzyk** [comment]
Thanks a lot for reporting this issue! I will take a look at this. From the first look, it looks like I didn't include changes to the web client in the "Structural Types" commit (https://github.com/moozzyk/SignalRSwiftCourse/commit/75a9fe47e5c84cb3ab0a0c35a533d7b348775aca).

**Comment by nysander** [comment]
hi Pawel, any updates on this?

it does also not build on dotnet 8 from brew

**Comment by moozzyk** [comment]
I created a commit to fix this: 82d4a5acd711c. I also linked to it from the lecture 8 resources. Finally, I inserted this commit after lecture 8. This required rewriting the history so you need to account for this when pulling.

For this course I recommend downloading and installing .NET from the official page at Microsoft. I am not sure why the code wouldn't build using the brew version but I haven't never tested the code with it.

**Comment by nysander** [comment]
Thanks a lot. This is second time I will be using your library. Course was good refesher. I managed to apply fixes on my own before you have written.

**Comment by moozzyk** [comment]
I am glad to hear you found the course useful.
